auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/tree/usr/bin/3g-dialer b/tree/usr/bin/3g-dialer
--- a/tree/usr/bin/3g-dialer
+++ b/tree/usr/bin/3g-dialer
@@ -261,12 +261,12 @@ device_modem_select(){
 	    if $guitool --question --text="$( eval_gettext "Did your device connect correctly?" )" ; then
 
 		local _message
-		_message="$( printf "$( eval_gettext "Device %s has a valid configuration, but it is not recognized. Is your modem connected correctly? Try to unplug it and plug it back. If necessary, reboot your computer. Otherwise create a new configuration." "$device" )" )"
+		_message="$( printf "$( eval_gettext "Device %s has a valid configuration, but is not recognized. Is your modem connected correctly? Try to unplug it and plug it back. If necessary, reboot your computer. Otherwise create a new configuration." "$device" )" )"
                 $guitool --error --text="$_message"
 
 		exit_me 1
             else
-		$guitool --info --text="$( eval_gettext "Plug it in your computer and wait 20 seconds before you continue" )"
+		$guitool --info --text="$( eval_gettext "Plug the modem into your computer and wait 20 seconds before you continue." )"
             fi
         fi
     fi
@@ -320,7 +320,7 @@ device_modem_select(){
         if [[ "$( echo "${device}" | wc -l)" -gt "1" ]] ; then
             el_explain 2 "multiple modems found, pick one"
             # pick one
-	    device_pick="$( echo "$device" | $guitool --list --text="$( eval_gettext "Multiple modems found.\nSelect one from the list, and if it does not work,\ntry another one." )" --column="$( eval_gettext "Device:" )" --height="280" || echo cancel )"
+	    device_pick="$( echo "$device" | $guitool --list --text="$( eval_gettext "Multiple modems found.\nSelect one from the list, and if this does not work,\ntry another one." )" --column="$( eval_gettext "Device:" )" --height="280" || echo cancel )"
 
 			if [[ "${device_pick}" = "cancel" ]] ; then
 			   exit_me 1
@@ -587,7 +587,7 @@ device_pin_status(){
         if grep -qE "(not specify a valid modem device)" "$logs" ; then
             kill_pid "${pid_wvdial}"
             kill_pid "${pid_gui}"
-	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration" )"
+	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration," )"
             exit_me 1
         fi
 
@@ -693,7 +693,7 @@ device_pin_set(){
             killall wvdial
 
 	    local translated_message
-	    translated_message="$( printf "$( eval_gettext "PIN %s is wrong. Please try again." )" "$device_pin" )"
+	    translated_message="$( printf "$( eval_gettext "Wrong PIN %s. Please try again." )" "$device_pin" )"
             $guitool --error --text="$translated_message"
 
             unset device_pin
@@ -752,7 +752,7 @@ device_pin_set(){
         if grep -qE "(not specify a valid modem device)" "$logs" ; then
             kill_pid "${pid_wvdial}"
             kill_pid "${pid_gui}"
-	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration" )"
+	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration," )"
             exit_me 1
         fi
 
@@ -812,7 +812,7 @@ device_pin_request(){
     # verify validity
     if [[ ! "${#pin}" = "4" ]] || [[ "$pin" = *[^0-9]* ]] ; then
         unset pin device_pin
-	$guitool --error --text="$( eval_gettext "PIN can only be a value of 4 digits - no letters or other characters. Please try again." )"
+	$guitool --error --text="$( eval_gettext "PIN can only consist of 4 digits - no letters or other characters. Please try again." )"
 
         unset device_pin
         $FUNCNAME
@@ -866,7 +866,7 @@ EOF
     if grep -q "^Init.*PUKCODE.*PINCODE" "${wvdialrc}" ; then
 	$guitool --question --text="$( eval_gettext "3 wrong attempts entering your PIN, please enter your PUK." )" || exit_me 0
 
-	values="$( $guitool --forms --text="$( eval_gettext "Insert PUK and new PIN:" )" --add-entry="PUK ""$( eval_gettext "Key:" )" --add-entry="$( eval_gettext "New:" )"" PIN" || exit_me 0 )"
+	values="$( $guitool --forms --text="$( eval_gettext "Enter PUK and new PIN:" )" --add-entry="PUK ""$( eval_gettext "Key:" )" --add-entry="$( eval_gettext "New:" )"" PIN" || exit_me 0 )"
         if [[ "${values}" = *"|"* ]] ; then
             puk="$( echo "$values" | awk -v FS="|" '{print $1}' )"
             pin="$( echo "$values" | awk -v FS="|" '{print $2}' )"
@@ -905,7 +905,7 @@ EOF
         fi
 
     else
-	$guitool --error --text="$( eval_gettext "You need to restore the PIN for your SIM card. Take the SIM card out of your modem and insert it in a mobile phone. Enter the required PUK to unblock the PIN. You can find it in the information from your provider (box, website, shop, etc)." )"
+	$guitool --error --text="$( eval_gettext "You need to restore the PIN for your SIM card. Take the SIM card out of your modem and insert it in a mobile phone. Enter the required PUK to unblock the PIN. You can find the PUK in the information from your provider (box, website, shop, etc)." )"
         exit_me 1
     fi
 
@@ -960,7 +960,7 @@ EOF
 
     else
         full_list="$(providers_list_show_sorted "$lists" )"
-	selected="$( { echo -e "disconnect\n""$( eval_gettext "Disconnect:" )\n$( eval_gettext "Disconnect your connection:" )\nnull\n$( eval_gettext "New:" )\n$( eval_gettext "Not listed here." )" ; echo "$full_list" ; sleep 1 ; echo "" ; } | $guitool --list --column="File" --column="$( eval_gettext "Country:" )" --column="$( eval_gettext "Provider:" )" --hide-column=1 --text="$( eval_gettext "Select the desired provider and country prefix." )" --height="420" --width="440" || echo cancel )"
+	selected="$( { echo -e "disconnect\n""$( eval_gettext "Disconnect:" )\n$( eval_gettext "End your connection:" )\nnull\n$( eval_gettext "New:" )\n$( eval_gettext "Not listed here." )" ; echo "$full_list" ; sleep 1 ; echo "" ; } | $guitool --list --column="File" --column="$( eval_gettext "Country:" )" --column="$( eval_gettext "Provider:" )" --hide-column=1 --text="$( eval_gettext "Select the desired provider and country prefix." )" --height="420" --width="440" || echo cancel )"
 
         if [[ "$selected" = "disconnect" ]] ; then
             exit_me 1
@@ -1185,7 +1185,7 @@ EOF
 done
 
 if ! ((is_connected)) ; then
-    $guitool --error --text="$( eval_gettext "Connection failed. Check log file in:" )""\n${logs} ""$( eval_gettext "which has information that can be useful. Else we suggest that you create your own configuration, if the one provided does not work. You can easily find it on Google using a search term like this:" )""'wvdial OR linux configuration OR apn ${provider}', ""$( eval_gettext "then just go to the option 'not listed here' to add your settings. If you think that you can help to improve this tool ,please refer to the Elive website." )"
+    $guitool --error --text="$( eval_gettext "Connection failed. Check log file in:" )""\n${logs} ""$( eval_gettext "which has information that can be useful. Else we suggest that you create your own configuration, if the one provided does not work. You can easily find it on Google using a search term like this:" )""'wvdial OR linux configuration OR apn ${provider}', ""$( eval_gettext "Then just go to the option 'not listed here' to add your settings. If you think that you can help to improve this tool, please refer to the Elive website," )"
 fi
 
 
@@ -1220,7 +1220,7 @@ device_busy(){
     if [[ "${device_busy_counter}" -gt "20" ]] || ((is_device_busy)) ; then
         kill_pid "all"
 
-	$guitool --error --text="$( eval_gettext "Your device does not respond. Please remove it, plug it back in and try to connect again. If this is unsuccessful, try a new configuration.." )"
+	$guitool --error --text="$( eval_gettext "Your device does not respond. Please remove it, plug it back in and try to connect again. If this is unsuccessful, try a new configuration." )"
         exit_me 1
     else
         el_explain 2 "device not enough busy for quit, adding counter"
@@ -1492,7 +1492,7 @@ main(){
                     ;;
                 new_configuration_own)
 
-		    $guitool --info --text="$( eval_gettext "You will now create your own configuration.  This is necessary when you have no template from your provider or when you cannot connect. You can very easily find the required configuration parameters for your provider and country by looking them up on Google using the search terms: wvdial or apn." )"
+		    $guitool --info --text="$( eval_gettext "You will now create your own configuration.  This is necessary when you have no connection information from your provider or when you cannot connect. You can very easily find the required configuration parameters for your provider and country by looking them up on Google using the search terms: wvdial or apn." )"
 
                     el_explain 2 "cleaning some values"
                     unset device is_pin_needed is_conf_valid provider device_pin
