auto: untarzanice | PLEASE review this commit @Thanatermesis

diff --git a/tree/usr/bin/3g-dialer b/tree/usr/bin/3g-dialer
--- a/tree/usr/bin/3g-dialer
+++ b/tree/usr/bin/3g-dialer
@@ -239,7 +239,7 @@ device_modem_select(){
 
     if ((is_configuration_new)) && ! ((is_progress_disabled)) ; then
         { echo 10 ; sleep 40 ; } \
-	    | $guitool --progress --text="$( eval_gettext "Detecting your modem..." )" --pulsate &
+	    | $guitool --progress --text="$( eval_gettext "Detecting modem..." )" --pulsate &
         pid=$!
     fi
 
@@ -260,7 +260,7 @@ device_modem_select(){
         done
 
         if ! ((is_device_found)) ; then
-	    if $guitool --question --text="$( eval_gettext "Did your device connect correctly?" )" ; then
+	    if $guitool --question --text="$( eval_gettext "Was your device connected correctly?" )" ; then
 
 		local _message
 		_message="$( printf "$( eval_gettext "Device %s has a valid configuration, but is not recognized. Is your modem connected correctly? Try unplugging it and plugging it back in. If necessary, reboot your computer. Otherwise, create a new configuration." "$device" )" )"
@@ -268,7 +268,7 @@ device_modem_select(){
 
 		exit_me 1
             else
-		$guitool --info --text="$( eval_gettext "Plug the modem into your computer and wait 20 seconds before you continue." )"
+		$guitool --info --text="$( eval_gettext "Plug the modem into your computer and wait 20 seconds before proceeding." )"
             fi
         fi
     fi
@@ -322,7 +322,7 @@ device_modem_select(){
         if [[ "$( echo "${device}" | wc -l)" -gt "1" ]] ; then
             el_explain 2 "multiple modems found, pick one"
             # pick one
-	    device_pick="$( echo "$device" | $guitool --list --text="$( eval_gettext "Multiple modems found.\nSelect one from the list, and if this does not work,\ntry another one." )" --column="$( eval_gettext "Device" )" --height="280" || echo cancel )"
+	    device_pick="$( echo "$device" | $guitool --list --text="$( eval_gettext "Multiple modems detected.\nSelect one from the list. If it doesn't work, try another." )" --column="$( eval_gettext "Device" )" --height="280" || echo cancel )"
 
 			if [[ "${device_pick}" = "cancel" ]] ; then
 			   exit_me 1
@@ -421,7 +421,7 @@ EOF
             el_error "modem not found."
             el_explain 0 "XXInfo:XX If it is connected and you see it like a __cdrom__ device, try to eject it before"
 
-	    $guitool --error --text="$( eval_gettext "Modem or phone not found, are you sure it is connected? Try to unplug and plug it back in. If your modem is recognized as a CDROM, eject it first. If this is unsuccessful, look for information on Google or report the bug to Elive." )"
+	    $guitool --error --text="$( eval_gettext "Modem or phone not detected. Ensure it's properly connected. Try unplugging and replugging. If recognized as a CDROM, eject it. If problems persist, search for solutions on Google or report a bug to Elive." )"
             exit_me 0
         else
             el_explain 2 "waiting 20 seconds..."
@@ -522,7 +522,7 @@ device_pin_status(){
 
     if ((is_pin_entered)) && ! ((is_progress_disabled)) ; then
         { sleep 1 ; echo 10 ; sleep 1000 ; } \
-	    | $guitool --progress --auto-kill --text="$( eval_gettext "Verifying PIN" )" --pulsate &
+	    | $guitool --progress --auto-kill --text="$( eval_gettext "Verifying PIN..." )" --pulsate &
         pid_gui=$!
     fi
 
@@ -589,7 +589,7 @@ device_pin_status(){
         if grep -qE "(not specify a valid modem device)" "$logs" ; then
             kill_pid "${pid_wvdial}"
             kill_pid "${pid_gui}"
-	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration," )"
+	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select 'New Configuration'," )"
             exit_me 1
         fi
 
@@ -659,7 +659,7 @@ device_pin_set(){
 
     if ! ((is_progress_disabled)) ; then
 	local _message
-	_message="$( printf "$( eval_gettext "Setting the PIN '%s' in your modem" )" "$device_pin" )"
+	_message="$( printf "$( eval_gettext "Setting PIN '%s' in your modem" )" "$device_pin" )"
 
         { sleep 1 ; echo 10 ; sleep 1000 ; } \
             | $guitool --progress --auto-kill --text="$_message" --pulsate &
@@ -695,7 +695,7 @@ device_pin_set(){
             killall wvdial
 
 	    local translated_message
-	    translated_message="$( printf "$( eval_gettext "Wrong PIN %s. Please try again." )" "$device_pin" )"
+	    translated_message="$( printf "$( eval_gettext "Incorrect PIN %s. Please try again." )" "$device_pin" )"
             $guitool --error --text="$translated_message"
 
             unset device_pin
@@ -754,7 +754,7 @@ device_pin_set(){
         if grep -qE "(not specify a valid modem device)" "$logs" ; then
             kill_pid "${pid_wvdial}"
             kill_pid "${pid_gui}"
-	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select New Configuration," )"
+	    $guitool --error --text="$( eval_gettext "Your modem is not recognized. Select 'New Configuration'," )"
             exit_me 1
         fi
 
@@ -804,7 +804,7 @@ device_pin_request(){
     : ${device_pin:="1234-example"}
 
     # ask for pin to user
-    pin="$( $guitool --entry --entry-text="$device_pin" --text="$( eval_gettext "Please enter your PIN" )" || echo cancel )"
+    pin="$( $guitool --entry --entry-text="$device_pin" --text="$( eval_gettext "Please enter PIN" )" || echo cancel )"
 
     if [[ "${pin}" = "cancel" ]] ; then
         is_pin_needed=0
@@ -877,7 +877,7 @@ EOF
             if [[ "${#pin}" = "4" ]] && [[ "$pin" != *[^0-9]* ]] ; then
                 if [[ "${#puk}" -ge "6" ]] && [[ "$pin" != *[^0-9]* ]] ; then
 
-		    if $guitool --question --text="$( eval_gettext "You have entered the following information" ):""\nPUK = ${puk}\nPIN  = ${pin}\n\n""$( eval_gettext "Please confirm that your information is entered correctly before you continue. Your SIM card will be restored shortly." )" ; then
+		    if $guitool --question --text="$( eval_gettext "You have entered the following details" ):""\nPUK = ${puk}\nPIN  = ${pin}\n\n""$( eval_gettext "Please confirm your information is correct before proceeding. Your SIM card will be restored soon." )" ; then
 
                         sed -i "/^Init.*PUKCODE.*PINCODE/s/PUKCODE\",\"PINCODE/${puk}\",\"${pin}/g" "${wvdialrc}"
 
@@ -900,14 +900,14 @@ EOF
             fi
 
             # seems like valures are wrong, exit
-	    $guitool --error --text="$( eval_gettext "Wrong input. Please try again." )"
+	    $guitool --error --text="$( eval_gettext "Invalid input. Please try again." )"
             $FUNCNAME
 
             exit_me 0
         fi
 
     else
-	$guitool --error --text="$( eval_gettext "You need to restore the PIN for your SIM card. Take the SIM card out of your modem and insert it in a mobile phone. Enter the required PUK to unblock the PIN. You can find the PUK in the information from your provider (box, website, shop, etc)." )"
+	$guitool --error --text="$( eval_gettext "To restore your SIM card's PIN, remove the SIM from your modem and insert it into a mobile phone. Use the PUK to unlock the PIN. Find the PUK in your provider's information (box, website, shop, etc.)." )"
         exit_me 1
     fi
 
@@ -962,7 +962,7 @@ EOF
 
     else
         full_list="$(providers_list_show_sorted "$lists" )"
-	selected="$( { echo -e "disconnect\n""$( eval_gettext "Disconnect" )\n$( eval_gettext "End your connection" )\nnull\n$( eval_gettext "New" )\n$( eval_gettext "Not listed here." )" ; echo "$full_list" ; sleep 1 ; echo "" ; } | $guitool --list --column="File" --column="$( eval_gettext "Country" )" --column="$( eval_gettext "Provider" )" --hide-column=1 --text="$( eval_gettext "Select the desired provider and country prefix." )" --height="420" --width="440" || echo cancel )"
+	selected="$( { echo -e "disconnect\n""$( eval_gettext "Disconnect" )\n$( eval_gettext "End connection" )\nnull\n$( eval_gettext "New" )\n$( eval_gettext "Not listed here." )" ; echo "$full_list" ; sleep 1 ; echo "" ; } | $guitool --list --column="File" --column="$( eval_gettext "Country" )" --column="$( eval_gettext "Provider" )" --hide-column=1 --text="$( eval_gettext "Select your desired provider and country prefix." )" --height="420" --width="440" || echo cancel )"
 
         if [[ "$selected" = "disconnect" ]] ; then
             exit_me 1
@@ -991,7 +991,7 @@ EOF
     # apn {{{
     if [[ -z $Apn ]] || ((is_configuration_own)) ; then
 	$guitool --info --text="$( eval_gettext "The APN (Access Point Name) is crucial to know to connect to the Internet. If you're unsure, ask your provider or search on Google using terms like 'Internet', 'web.vodafone.de', or 'movistar.es'. You can also leave the input field empty." )"
-	Apn=$( $guitool --entry --entry-text="internet" --text="$( eval_gettext "Enter the APN (Access Point Name) of your provider." )" || echo cancel )
+	Apn=$( $guitool --entry --entry-text="internet" --text="$( eval_gettext "Enter your provider's APN (Access Point Name)." )" || echo cancel )
     fi
 
     if [[ "$Apn" = "cancel" ]] ; then
@@ -1020,7 +1020,7 @@ EOF
 
     if echo "$Password" | grep -q phonenumber ; then
         if [[ -z "$phonenumber" ]] ; then
-	    phonenumber="$( $guitool --entry --text="$( eval_gettext "Please enter the phone number to connect to" )" || echo cancel )"
+	    phonenumber="$( $guitool --entry --text="$( eval_gettext "Please enter the phone number for connection" )" || echo cancel )"
         fi
         Password="${Password/phonenumber/$phonenumber}"
     fi
@@ -1053,7 +1053,7 @@ EOF
     fi
 
     if [[ -z "$stupid" ]] ; then
-	if $guitool --question --text="$( eval_gettext "Do you want to use the Stupid Mode? Some providers are not smart enough to give your modem the required information for a connection. When you have problems with random disconnections, create a new configuration in the Stupid Mode. Recommended!" )" ; then
+	if $guitool --question --text="$( eval_gettext "Would you like to use Stupid Mode? Some providers may not provide the necessary information for modem connections, leading to random disconnections. Creating a new configuration in Stupid Mode can help. Recommended!" )" ; then
             stupid=Yes
         else
             stupid=No
@@ -1171,7 +1171,7 @@ EOF
     fi
 
 
-    { while test -f "$progress_file" ; do cat "$progress_file" ; sleep 0.3 ; done ; } | { $guitool --progress --auto-close --text="$( eval_gettext "Elive is trying to connect,\nusing configuration:\n\nPhone" )"" '${phone}'\nAPN: '${apn}'\nWith Username: ${usernames}\nWith auto-dns"" ${dns}\nUsing 'stupid mode' provider: ${stupid}\n\n""$( eval_gettext "Please be patient...\nTrying to connect" )" || echo EXIT_NOW > "${connected}" ; } &
+    { while test -f "$progress_file" ; do cat "$progress_file" ; sleep 0.3 ; done ; } | { $guitool --progress --auto-close --text="$( eval_gettext "Elive is trying to connect,\nusing configuration:\n\nPhone" )"" '${phone}'\nAPN: '${apn}'\nWith Username: ${usernames}\nWith auto-dns"" ${dns}\nUsing 'stupid mode' provider: ${stupid}\n\n""$( eval_gettext "Please wait...\nAttempting to connect" )" || echo EXIT_NOW > "${connected}" ; } &
 
     is_connection_trying=1
 
@@ -1187,7 +1187,7 @@ EOF
 done
 
 if ! ((is_connected)) ; then
-    $guitool --error --text="$( eval_gettext "Connection failed. Check log file in" )""\n${logs} ""$( eval_gettext "which has information that can be useful. Else we suggest that you create your own configuration, if the one provided does not work. You can easily find it on Google using a search term like this" )""'wvdial OR linux configuration OR apn ${provider}', ""$( eval_gettext "Then just go to the option 'not listed here' to add your settings. If you think that you can help to improve this tool, please refer to the Elive website," )"
+    $guitool --error --text="$( eval_gettext "Connection failed. Please check the log file located in" )""\n${logs} ""$( eval_gettext "which contains useful information. If the provided configuration doesn't work, we suggest creating your own. Easily find it on Google using a search term like this" )""'wvdial OR linux configuration OR apn ${provider}', ""$( eval_gettext "Simply select 'not listed here' to add your settings. If you believe you can improve this tool, please visit the Elive website for more information," )"
 fi
 
 
@@ -1222,7 +1222,7 @@ device_busy(){
     if [[ "${device_busy_counter}" -gt "20" ]] || ((is_device_busy)) ; then
         kill_pid "all"
 
-	$guitool --error --text="$( eval_gettext "Your device does not respond. Please remove it, plug it back in and try to connect again. If this is unsuccessful, try a new configuration." )"
+	$guitool --error --text="$( eval_gettext "Your device is unresponsive. Remove it, plug it back in, and try connecting again. If unsuccessful, try a new configuration." )"
         exit_me 1
     else
         el_explain 2 "device not enough busy for quit, adding counter"
@@ -1320,7 +1320,7 @@ device_connect(){
     kill_pid "$pid_connecting_gui"
 
     if ! ((is_connected)) && [[ "${FUNCNAME[1]}" = "main" ]] ; then
-	selected="$( echo -e "retry\n$( eval_gettext "Please try again" )\nconfig_new\n$( eval_gettext "New configuration" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Could not connect. Please select an option" )" --height="240" --width="340" || echo cancel )"
+	selected="$( echo -e "retry\n$( eval_gettext "Try again, please." )\nconfig_new\n$( eval_gettext "New configuration" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Unable to connect. Please select an option to proceed." )" --height="240" --width="340" || echo cancel )"
        case "$selected" in
            cancel)
                if ((message_carrier_no)) ; then
@@ -1354,7 +1354,7 @@ connected_wait_for_prompt(){
 
     if ! ((is_progress_disabled)) ; then
         { sleep 1 ; echo 10 ; sleep 1000 ; } \
-	    | $guitool --progress --text="$( eval_gettext "Connected, waiting for authorization" )" --pulsate &
+	    | $guitool --progress --text="$( eval_gettext "Connected, awaiting authorization" )" --pulsate &
         pid_prompt_gui=$!
     fi
 
@@ -1387,7 +1387,7 @@ connected_successfully(){
 
     el_explain 0 "connected successfully"
     if ! ((is_progress_disabled)) ; then
-	$timeout $guitool --info --text="$( eval_gettext "You have successfully connected to the Internet" )"
+	$timeout $guitool --info --text="$( eval_gettext "Successfully connected to the Internet" )"
     fi
 
     # FIXME: set a counter of network usage
@@ -1463,9 +1463,9 @@ main(){
             config_get
 
             if ((is_conf_valid)) ; then
-		selected="$( echo -e "connect\n$( eval_gettext "Connecting to" ) ${provider}\ndisconnect\n$( eval_gettext "Disconnect from" ) $provider\nnew_profile\n$( eval_gettext "New connection" )\nnew_configuration_own\n$( eval_gettext "New manual connection" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Please select an option" )" --height="240" --width="340" || echo cancel )"
+		selected="$( echo -e "connect\n$( eval_gettext "Connecting to" ) ${provider}\ndisconnect\n$( eval_gettext "Disconnect from" ) $provider\nnew_profile\n$( eval_gettext "New connection" )\nnew_configuration_own\n$( eval_gettext "New manual connection" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Please choose an option" )" --height="240" --width="340" || echo cancel )"
             else
-		selected="$( echo -e "new_profile\n$( eval_gettext "New connection" )\nnew_configuration_own\n$( eval_gettext "New manual connection" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Please select an option" )" --height="190" --width="340" || echo cancel )"
+		selected="$( echo -e "new_profile\n$( eval_gettext "New connection" )\nnew_configuration_own\n$( eval_gettext "New manual connection" )" | $guitool --list --column="" --column="$( eval_gettext "Options" )" --hide-column=1 --text="$( eval_gettext "Please choose an option" )" --height="190" --width="340" || echo cancel )"
 
             fi
 
@@ -1480,11 +1480,11 @@ main(){
                     if [[ -n "${provider}" ]] ; then
 
 			local translated_message
-			translated_message="$( printf "$( eval_gettext "Disconnected from %s" )" "$provider" )"
+			translated_message="$( printf "$( eval_gettext "Disconnected from %s successfully." )" "$provider" )"
                         $guitool --info --text="$translated_message"
 
                     else
-			$guitool --info --text="$( eval_gettext "Disconnected successfully." )"
+			$guitool --info --text="$( eval_gettext "Successfully disconnected." )"
                     fi
 
                     ;;
